name: Script Scraping Match Masters

on:
  schedule:
    # Exécution à la minute 50 toutes les 4 heures (00:50, 04:50, 08:50, etc.)
    - cron: '50 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installer les librairies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 cloudscraper firebase-admin

    - name: Lancer le scraper Match Masters
      env:
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: python scraper.py

    - name: Sauvegarder les modifications dans le dépôt
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scrapmatchmasters.json
        git commit -m "Mise à jour automatique Match Masters : $(date +'%Y-%m-%d')" || exit 0
        git push
